### ISSUE TITLE
Refactor field channels to work with new LearningPath model

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#103]
# Description/Context
The `channels_fields` app needs to be refactored to work with the `learning_resources.LearningPath` model instead of `course_catalog.UserList`

# Plan/Design
Start by replacing all references to `course_catalog.UserList` with `learning_resources.LearningPath` in the `field_ and fix whatever breaks from there.

**Comment by ChristopherChudzicki** [comment]
Closed by #196
