### ISSUE TITLE
Separation of concerns: Use pluggy to handle triggering of search index updates

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#108]
# Description/Context
Use pluggy (or some other alternative) to trigger search index updates whenever LearningResource objects are created, updated, or deleted.

Depends on https://github.com/mitodl/mit-open/issues/111 beign completed first.

# Plan/Design
https://github.com/mitodl/hq/discussions/1638

@rhysyngsun does this use case fit into what you had in mind for the RFC?

**Comment by rhysyngsun** [comment]
@mbertrand could you give me some more context as to the problem you're trying to solve?

**Comment by mbertrand** [comment]
Current (old) approach:

```
# Create or update a resource
learning_resource, created = LearningResource.objects.update_or_create(....)
# Now index the resource via a helper function that calls a task
index_resource(learning_resource)

# Unpublish a resource
learning_resource.published = False
learning_resource.save()
# Now deindex the resource via a helper function that calls a task
deindex_resource(learning_resource)
```

Example: https://github.com/mitodl/mit-open/blob/main/learning_resources/etl/loaders.py#L255-L258

New approach - don't manually trigger an index/deindex via a line of code like above, use pluggy instead?
