### ISSUE TITLE
Rich Text Editor

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#109]
# User Story

As a staff member, I want to create rich-text content to be displayed on MIT Open.

# Description/Context
We want to enable staff users to create rich-text content without assistance from engineering (example: A highlight on new courses on Generative AI).

# Acceptance Criteria

- [x] Propose and implement a model for model for storing rich-text content.
- [x] Expose the model with an API
    - limited to some usergroup *conceptually "OL staff"*
- [x] Implement simple frontend such as `/post/:id` and `/post/:id/edit` for viewing/editing the rich text content. 
    - A CKEditor component already exists on the frontend. See http://discussions-rc.odl.mit.edu/infinite/article. *The [corresponding page](https://mit-open-rc.odl.mit.edu/infinite/article) on mit-open-rc is broken at th moment, I believe due to a missing environment variable.*

# Plan/Design

- **Continue using CKEditor**: In the past we have used CKEditor for rich-text editing in Open Discussions and Studio. It's works well out-of-the-box and is extensible, so we should continue using it.
- **Data Storage**: CKEditor's natural output format is HTML. Let's store data as HTML. (Not as markdown, as in OCW Studio, or as JSON, as in Open Discussions.)
    - **Concern:** We should sanitize the HTML before storing to db, using something like [nh3](https://github.com/messense/nh3)

**Comment by ChristopherChudzicki** [comment]
@ferdi For this initial work, I think it makes sense to keep the data model pretty limited:
```python
class StaffPost(TimestampedModel):
    """
    Stores rich-text content created by staff members.
    """

    html = models.TextField()
    title = models.CharField(max_length=255)
```

We could additionally store author id, although based on the use case we discussed, it seems like the API permission should be similar to LearningPaths—all members of some group ("staff") can create/edit/delete, others can only view.

Is there any additional data that you think it makes sense to store/edit for now?

<img width="1582" alt="Screenshot 2023-10-02 at 3 53 29 PM" src="https://github.com/mitodl/mit-open/assets/9010790/0786fa51-4486-44e9-b7dd-9f63678a7256">

**Comment by Ferdi** [comment]
As simple as possible. we can always add stuff.
