### ISSUE TITLE
Displaying price on learning resources

### ISSUE THREAD

**Issue by jonkafton** [mitodl/mit-open#1098]
### User Story

We display the price of a learning resource alongside a "Certificate" badge where certification is available.

Some courses can be taken for free, but have the option of a paid-for certification.

These courses display as "Certificate" Free, which is misleading as can be interpreted that the certificate is free:

<img width="230" alt="image" src="https://github.com/mitodl/mit-open/assets/939376/cfb1dba0-b67a-4fc5-ab10-9d27a6a812dd">

The task is to resolve this with the correct UX and presentation of the data returned from the API. The cost for the certificate should be displayed alongside the certificate badge separately from the price of the resource.

### Description/Context

Some details and facts:

- Sloan courses can never be free
- Most MITx courses are Free AND "certificate if you pay"
- When price is missing it should say "Paid"
- The learning resource APIs return `free` and `certification` flags
  - free=true: you can take the course for free
  - free=false: you cannot take the course for free
  - certification=true: You can pay for a certificate (this is never free)
  - certification=false: No certificate available (edited) 

- https://mitopen.odl.mit.edu/search/?resource=14037 is displayed as follows, but is not free:
<img width="864" alt="image" src="https://github.com/mitodl/mit-open/assets/939376/1dabc471-4b3b-4c03-b8dc-f5f7e2c9f7f0">

- Free MITx programs with an option for paid certification should display "Certificate($some_amount)   Free": https://mitopen.odl.mit.edu/search/?certification_type=completion&offered_by=mitx&resource_type=program

- Free MITx courses with an options for paid certification are displaying the certification cost as the course cost and should display  "Certificate ($49)  Free": https://mitopen.odl.mit.edu/search/?certification_type=completion&offered_by=mitx&resource_type=course

- Courses are one of:
  - free with no certificate
  - free with paid certificate option
  - one price includes certificate

**Comment by ChristopherChudzicki** [comment]
Associated slack thread: https://mitodl.slack.com/archives/C03K5HYGPT9/p1718631136889579
