### ISSUE TITLE
Change field name for LearningResourcePlatform.platform

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#113]
# Description/Context
A better field name for `LearningResourcePlatform.platform` would be `LearningResourcePlatform.platform_code`.  Change it and all affected code.

**Comment by Ferdi** [comment]
What's in your mind, why this change ?

**Comment by mbertrand** [comment]
It was a [suggested change in this PR](https://github.com/mitodl/mit-open/pull/99#discussion_r1341481858) and I agree it is a less confusing name, but changing it will require modifying lots of files which is why I decided to create a new issue for it rather than include it in the PR, especially since the current name was assigned much earlier.
