### ISSUE TITLE
Set SOCIAL_AUTH_OL_OIDC_SECRET in Heroku

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#119]
## Expected Behavior
Should be able to log in to MIT Open via keycloak.

## Current Behavior
Can't login via keycloak—500 error.

## Steps to Reproduce
1. Try logging in via https://mit-open-rc.odl.mit.edu/login/ol-oidc/. 

## Possible Solution
Set `SOCIAL_AUTH_OL_OIDC_SECRET` in Heroku. *In some way that it doesn't get unset.*

## Additional Details
This has been set manually in heroku, but seems to get cleared. What's the right way to set secrets?

**Comment by collinpreston** [comment]
https://github.com/mitodl/salt-ops/blob/main/pillar/heroku/mitopen.sls#L73

**Comment by collinpreston** [comment]
https://github.com/mitodl/salt-ops/blob/main/pillar/heroku/mitopen.sls#L36

**Comment by collinpreston** [comment]
Resolved via DevOps.
