### ISSUE TITLE
Implement Video model and API 

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#12]
Implement a new `Video` model and API based on the new LearningResource models

#### Designs and Mockups

https://github.com/mitodl/mit-open/issues/4

#### Acceptance Criteria:

- [ ] Video model, serializers, views, etc and any supporting models/functions are implemented
- [ ] Videos and video playlists are searchable as learning resources

**Comment by mbertrand** [comment]
@pdpinch @ferdi should I close this issue?

**Comment by mbertrand** [comment]
This will be implemented similarly to the video ETL in open-discussions, with videos imported from channels/playlists specified in https://github.com/mitodl/open-video-data.  However, that repo needs to be updated to be more selective about which channels/playlists are included.

**Comment by pdpinch** [comment]
@mbertrand what remains to be done here?

**Comment by mbertrand** [comment]
Closed by https://github.com/mitodl/mit-open/pull/558
