### ISSUE TITLE
Keycloak integration - Password change UX

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mit-open#129]
# User Story
As a user, I should be able to navigate to a password change URL which will redirect me to the proper Keycloak page for changing my password.

# Description/Context
This implementation should be similar to what was done for https://github.com/mitodl/open-discussions/pull/4234.

# Plan/Design
https://docs.google.com/document/d/17tJ-C2EwWoSpJWZKjuhMVgsqGtyPH0IN9KakXvSKU0M/edit#heading=h.cd9rql6ndhlp

**Comment by sovsey** [comment]
Closing as this functionality is currently usable in current site version.
