### ISSUE TITLE
OCW courses with original topic "Programming Languages" not assigned PMT topic "Programming & Coding"

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#1339]
### Expected Behavior
OCW courses with the original topic "Programming Languages" should be assigned the topic "Programming & Coding" in MIT Open.

### Current Behavior
[This OCW course](https://ocw.mit.edu/courses/6-189-a-gentle-introduction-to-programming-using-python-january-iap-2008/data.json) is not assigned that topic; none are and the [topic channel](https://mitopen.odl.mit.edu/c/topic/programming-coding/) returns no results.

### Steps to Reproduce
Locally, set "OCW_" and "AWS_" env settings to the same as RC, then run `python manage.py backpopulate_ocw_data --overwrite --skip-contentfiles --course-name 6-189-a-gentle-introduction-to-programming-using-python-january-iap-2008`

**Comment by pdpinch** [comment]
In a related issue, I think the edX mapping should be updated to map "Computer Science" to both "Computer Science" **and** "Programming and Coding" because, in practice, all the edX courses on "Computer Science" cover coding. 

Let me know if we should open a new issue for this.

**Comment by jkachel** [comment]
The OCW pipeline only considers topics up to two levels deep - for this course, the topic in question is at the third level. So, the fix is just to flatten all the topics that come back.

@pdpinch wrt mappings: I feel like that's a different issue, since that'd be an update to the topic data and this is a logic issue.

**Comment by mbertrand** [comment]
@sovsey I will go ahead and transfer it,  sometimes I forget to create the issue in hq instead of the repo it applies to.
