### ISSUE TITLE
Array filters for REST APIs

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#146]
# User Story
As a developer using MIT Open APIs, I want the ability to filter learning resources by multiple values: for example, `resource_type="course" or "program"`.

# Description/Context
Our Search API is being developed to support filter parameters with array values. To maintain consistency in our APIs, we should allow array filtering on other APIs that share the same filter parameters. 

# Acceptance Criteria
- [ ] Allow filtering by multiple values in `/api/v1/learning_resources/` (and its cousins, `/courses/`, /programs/`, etc).
- [ ] Decide on and document whether to [explode](https://swagger.io/docs/specification/serialization/) parameters or not.
    - The choice should be consistent with across our APIs, including Search 

# Plan/Design
We are currently using `django-filter`, which has a [MultipleChoiceFilter](https://django-filter.readthedocs.io/en/stable/ref/filters.html#multiplechoicefilter) for this.

**Comment by mbertrand** [comment]
@ChristopherChudzicki I think https://github.com/mitodl/mit-open/pull/449 addressed this?

**Comment by ChristopherChudzicki** [comment]
@mbertrand I agree; closing.
