### ISSUE TITLE
Learning resource types should be displayed with spaces

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#149]
learning_path and podcast_episode should be displayed as "learning path" and "podcast episode"

**Comment by ChristopherChudzicki** [comment]
@abeglova This refers to the documentation, right? (e.g., at https://mit-open-rc.odl.mit.edu/api/v1/schema/redoc/#tag/learning_resources/operation/learning_resources_list)

**Comment by abeglova** [comment]
I think it refers to both the documentation and the api results.

**Comment by abeglova** [comment]
The resource_type that is saved in the database/displayed by the serializer for learning resources also has _ instead of a space
