### ISSUE TITLE
Offered_by: Include key in response and use key when filtering

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#158]
# Description/Context
We want to use ids rather than display names when filtering APIs. Currently:
- The search API uses display names when filtering `/learning_resources_earch?offered_by=sloan+executive+education`
- The catalog APIs use offered_by keys: `/courses?offered_by=see`.

We should use keys in both places.

# Plan/Design
Currently the responses only include offered_by display names: `"offered_by": "Sloan Executive Education"`. Probably we should include the offerer object, `{ key: "see", name: "Sloan Executive Education" }` in the API response. This will also facilitate allowing search to filter by key.

**Comment by mbertrand** [comment]
Makes sense to me, and I made some changes in another PR somewhat relevant to this (adding a `code` field to the `LearningResourceOfferor` model, linked above).

**Comment by mbertrand** [comment]
This was implemented at some point, so closing.

```
            "offered_by": {
                "code": "mitpe",
                "name": "Professional Education"
            },
```

https://mitopen-rc.odl.mit.edu/api/v1/learning_resources/?offered_by=mitpe
https://mitopen-rc.odl.mit.edu/api/v1/learning_resources_search/?offered_by=mitpe
