### ISSUE TITLE
Add an id filter to learning_resources_search

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#164]
In order to test the performance of the open search api compared to getting data directly from postgres we need an id filter in open search.

Additionally, opensearch has an internal document id that can be replaced with the learning resource id since learning resource ids are unique.

For now I will implement this as a filter similar to other existing filters.  Open search also supports a get operation for getting documents by id which I expect would be more efficient but that won't stack with other filters and it's probably not worth implementing a new endpoint for this yet.

**Comment by pdpinch** [comment]
@abeglova should this be closed?
