### ISSUE TITLE
Allow search API results to be sorted by department course numbers

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#195]
# User Story
When searching for resources, the user should be able to sort results by course number if desired.  When a department is selected, the sort should apply only to courses within that department.

# Description/Context
`sort_coursenum` was added to indexed course documents in #173.  The search API should allow sorting on that field if specified in query parameters.

This is a port of existing functionality from open-discussions.
- Issue: https://github.com/mitodl/open-discussions/issues/3453
- PR: https://github.com/mitodl/open-discussions/pull/3457 and https://github.com/mitodl/ocw-hugo-themes/pull/134

# Acceptance Criteria
- [ ] Search results for courses ordered by `sort_coursenum` if query parameter is passed. 
- [ ] Search results for courses ordered by `sort_coursenum` only within selected department(s) if any.

# Plan/Design
- Add an optional query parameter that the search API accepts to sort by `sort_coursenum`, ascending or descending.
- Make sure the option is documented in the API schema

**Comment by Ferdi** [comment]
What are current sort options for /search api ?

**Comment by mbertrand** [comment]
`id`, `readable_id`, `last_modified`, `runs.start_date` (ascending and desscending).

**Comment by mbertrand** [comment]
Old open-discussions issue, the functionality should work about the same here: https://github.com/mitodl/open-discussions/issues/3453

**Comment by Ferdi** [comment]
A good name for this field would be `mitcoursenumber` or `mitcoursenr` 

Unless there a reason the field to start with "sort_"?

**Comment by mbertrand** [comment]
> A good name for this field would be `mitcoursenumber` or `mitcoursenr`
> 
> Unless there a reason the field to start with "sort_"?

That's doable, I can adjust it.

**Comment by mbertrand** [comment]
@Ferdi you okay with making that `mit_course_num` or just `course_num`?  I feel it might be a bit more readable to add some underscores in there.
