### ISSUE TITLE
Refactor Sass styles to CSS-in-JS

### ISSUE THREAD

**Issue by jonkafton** [mitodl/mit-open#239]
# Description/Context

Both are currently used for css styling in the React app, though predominantly Sass (with SCSS syntax). [Sass](https://sass-lang.com/) is a styling language that compiles to CSS while providing additional capabilities for dynamic values (variables and interpolation), mixins for reusability and some basic control flow. The class name selector paths are preserved in the CSS build bundle and so are bound to the class attributes on the nested HTML elements that React writes to the DOM.

This limits modularity and separation of concerns for reusability and portability as a nested component that can otherwise be abstracted away from the app for reuse will depend on styles declared in its parent where they are specific to that component nested in the context of the parent.

CSS-in-JS is currently used in the ol-util workspace with [Styled-components](https://styled-components.com/), a library that enables CSS to be written alongside React components inside native JavaScript template literals. As they live in JavaScript, any procedural functionality can be applied natively. TypeScript definitions are also provided for type safety, editor type ahead and strongly typed theming.

Class names are hashed dynamically, removing brittleness around selector path matching and producing CSS files for the build that can be split according to concern and cached across versions where unchanged. Only the styles that are in use are compiled to the build output and only the styles for components actually rendered are injected onto the page, enhancing performance.

As the styles live next to their component, they are easy to keep track of, improving maintenance and making it simple to spot any dead styles not in use. Normal React composition can be used for specialization where a component uses specific styles within its parent context. styled-components uses the [STYLIS](https://github.com/thysultan/stylis) preprocessor for more advanced selector patterns should they be useful for nested components and while migrating from Sass.

[Emotion](https://emotion.sh/) is a library for CSS-in-JS that takes inspiration from Styled-components. It is framework agnostic (Styled-components is for React) though has a ['styled' API](https://emotion.sh/docs/@emotion/styled) that returns a React component from tagged template literals, a very useful pattern from Styled-components.

We would like to use Emotion in favor of Styled-components as we use [MUI](https://mui.com/) extensively, which imports Emotion (so it is already a project dependency and included in our build output) and [provides interoperability](https://mui.com/material-ui/guides/interoperability/#emotion).

# Plan/Design

We'll want to refactor out all Saas for a single consistent styling solution, removing all .scss files and Sass build processing. Given that structural rework is ongoing, the goal here is to create a baseline PR to serve as a reference point for refactoring styles to Emotion as we migrate code.

- Styles should be colocated with their components.

- The "styled" API should be used, e.g. from [ol-util](https://github.com/mitodl/mit-open/blob/b8b292418758b9caa580aaa0fa2289f8af40533e/frontends/ol-util/src/components/PageBanner.tsx#L54C7-L54C22).

```typescript
const BannerContainer = styled.div({
  position: "absolute",
  width: "100%",
  zIndex: -1
})
```

- Composition may be used for specialization, e.g.:

```typescript
const GreenBannerContainer = styled(BannerContainer){
    backgroundColor: "green"
})
```

- Styled-components should be removed as a dependency, replacing with Emotion. The only current use is in [ol-util](https://github.com/mitodl/mit-open/blob/main/frontends/ol-util).  It is also installed into [mit-open](https://github.com/mitodl/mit-open/blob/main/frontends/mit-open) and [ol-search-ui](https://github.com/mitodl/mit-open/blob/main/frontends/ol-search-ui), though unused.

## Theming

We have app level theme values defined in Saas in the mit-open workspace. These are not compatible with the [MUI theme schema](https://mui.com/material-ui/customization/theming/#theme-configuration-variables) - we current just specify a series of flat Sass variables, e.g.:

```scss
$color-gray-1: #fff;
$color-gray-2: #f0f5f7;
$color-gray-3: #b0b0b0;
$color-gray-4: #898a8b;
$color-gray-5: #000;
$color-red-1: #e3d5d5;
```

We may want to migrate them towards this schema, though this depends on whether we are fully invested in the [Material Design color system](https://m3.material.io/styles/color/system/overview) (open question).

We do however want to define the theme in a single place. Currently the MUI theming lives in ol-design, so this can be augmented with our custom theme values. We may want to move the theme back up to the mit-open workspace assuming it is specific to the application and should be passed down to components so they are reusable without imposing any theme, ie. components should specify their styles for layout, though choices for color, shading and so on should be provided by the parent.

- Object styles shown in examples above are preferred as they are type checked, though tagged template literal strings should be supported. These are particularly useful for dynamic theming where the styles are defined outside of components and the values need to be passed as React props for reactivity:

```typescript
const Component = styled.div`
  position: absolute;
  color: ${({ theme }) => theme.palette.primary.main};
`
```

- Nice to have - theme properties are inferred for type checking. Alternatively we will need to be imported and provided as generic type variable, ie. `ThemeProps`:

```typescript
const Component = styled.div<ThemeProps>`
  position: absolute;
  color: ${({ theme }) => theme.palette.primary.main};
`
```

If there is no requirement for reactivity (open question), the theme values can be simply imported and used in place in object styles, ie.:

```typescript
const Component = styled.div<ThemeProps>({
  position: "absolute",
  color: theme.palette.primary.main
})
```

**Comment by pdpinch** [comment]
Does this need a checklist of components to migrate?

**Comment by jonkafton** [comment]
The stylesheets have now all been replaced, with a couple of exceptions such as where we need them to style vendor libraries (CKEditor). I'll move this to done.
