### ISSUE TITLE
Add simple login / logout to frontend

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#241]
# User Story
As a user, I would like to be able to log in and out via frontend, and have visible indication as to whether I am logged in or out.

# Description/Context
Add a simple login / logout interface in top right corner of frontend, similar to what we had on https://discussions-rc.odl.mit.edu/. The login should redirect to relevant keycloak page (e.g., https://mit-open-rc.odl.mit.edu/login/ol-oidc/ on RC)

# Acceptance Criteria

- [ ] if user authenticated, a profile icon in top-right corner with dropdown to sign out.
- [ ] if user is not authenticated, a login button in to-right corner to sign out.

# Plan/Design
Similar to

<img width="174" alt="Screenshot 2023-11-21 at 10 11 55 AM" src="https://github.com/mitodl/mit-open/assets/9010790/56164f3b-c016-4e93-b62f-430b9b34af87">

**Comment by pedroclarkleite** [comment]
hey @pdpinch is this what you were looking for?
