### ISSUE TITLE
Disallow blank values in some LearningResource auxillary model fields:

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mit-open#255]
Some specifics that I noticed offhand after seeing I somehow ended up with blank values for all of my `LearningResourceOfferor.code` records. It doesn't make sense to allow for blank values in these fields because they either a) are used as a unique identifier or b) are a name/label used for display.

- `LearningResourcePlatform.code`
- `LearningResourcePlatform.name`
- `LearningResourceTopic.name`
- `LearningResourceOfferor.code`
- `LearningResourceOfferor.name`
- `LearningResourceDepartment.department_id`

**Comment by ChristopherChudzicki** [comment]
### Resolved

The ones mentioned above are much better now. I didn't track down all the changes, but some of them were in https://github.com/mitodl/mit-open/pull/240 :
- `LearningResourcePlatform.code` not nullable, pkey (unique)
- `LearningResourcePlatform.name` not nullable
- `LearningResourceTopic.name` not nullable, unique
- `LearningResourceOfferor.code` not nullable, pkey (unique)
- `LearningResourceOfferor.name` not nullable, unique
- `LearningResourceDepartment.department_id` not nullable, pkey (unique)

### For consideration

I did notice a few things that maybe could be improved:
- `LearningResourcePlatform.url` is currently nullable, I'm not sure if it should be. The ones on RC without URLs are `podcast, emeritus, simplilearn, globalalumni, susskind, whu`
- LearningResourece itself has a few nullable fields to handle edge cases:

    ```
    platform ... null for learningpaths
    offerer ... null for learningpaths, podcasts, podcastepisodes
    url ... null for learningpaths and resources with published: false
    ```

Each of the above nullable features was slightly surprising to me, but I also understand why they are the way they are. So, maybe nothing to do here.

**Comment by ChristopherChudzicki** [comment]
@rhysyngsun I'm going to close, but feel free to re-open if you disagree.
