### ISSUE TITLE
Implement and publish official API client(s) for internal and external reuse

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mit-open#269]
# Description

We want to publish official API clients for the Open APIs, generated from the OpenAPI schema. This will be both for internal and external usage. The approach outlined here in based on [this discussion](https://github.com/mitodl/hq/discussions/3112).

# Plan

- [x] Create a new monoprepo for mit-open clients
- [x] MIT Open should have OpenAPI schemas partitioned on an API version.
- [x] Configure this repo with the openapi-generator which generates API clients for languages we want to support.
  - Versioned API clients need to be available within the same package because with most dependency management systems you're generally permitted to only install 1 version of a package. So that means we probably need clients namespaced by version within each language package. For example, in Python it might look like: `ol_open_api.v1.APIClient`, `ol_open_api.v2.APIClient`, etc.
  - Let's start with typescript and python for now, since we know we need these.
  - The repo should be setup so it's easy to add more in the future.
- [x] Publishing of packages to their respective package indexes (pypi.org, npmjs.com, etc).

**Comment by pdpinch** [comment]
Do we have a plan for where this would be used?

**Comment by rhysyngsun** [comment]
@pdpinch mit-open and ocw would use it afaik, but really these would be the officially blessed clients that we would support for anyone integrating with the catalog APIs.

**Comment by ChristopherChudzicki** [comment]
One of the reasons I've brought this issue up lately is so we could use the client while updating course-search-utils. *Possibly not the actual API clients (though possibly), but definitely the typescript definitions will be useful.*

**Comment by rhysyngsun** [comment]
Package has been published: https://www.npmjs.com/package/@mitodl/open-api-axios
