### ISSUE TITLE
Add basic homepage

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#27]
Add a basic homepage for `mit-open` using new OpenAPI-generated types and API client.

- demonstrate mocking generated API client in tests
- test data factories using new types
- Basic UI similar to what we have now at https://discussions-rc.odl.mit.edu/infinite, but with just one courses carousel for now.

**Comment by rhysyngsun** [comment]
@ChristopherChudzicki can you assign yourself and move to in progress on the board when you start?

**Comment by ChristopherChudzicki** [comment]
Done in #37 and #49
