### ISSUE TITLE
content_category is not populated for content files

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#278]
This is the "resource type" in the sidebar for OCW search
https://ocw.mit.edu/search/?r=Readings&r=Tools&type=resourcefile. To avoid confusion with the resource_type field it is renamed content_category. Currently it's always null

Currently the value is always null
https://mit-open-rc.odl.mit.edu/api/v1/content_file_search/?aggregations=content_category

**Comment by mbertrand** [comment]
This serializer function needs to be fleshed out:

```
    def get_content_category(self, instance):  # noqa: ARG002
        """
        Get the file type of the ContentFile. For now, just return None.
        NOTE: This function needs to be updated once OCW courses are added.
        """
        return
 ```
 
 likely based on[ this old one from open-discussions](https://github.com/mitodl/open-discussions/blob/master/search/serializers.py#L385-L394).
