### ISSUE TITLE
improve usability of api/v1/learning_resources/[parent_id]/items/ and api/v1/learning_resources/[parent_id]/items/[relationship id]

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#280]
Currently the api/v1/learning_resources/[parent_id]/items/[relationship id] endpoint requires the id of the LearningResourceRelationship to access. This is not exposed anywhere else in the api. The id values returned  by api/v1/learning_resources/[parent_id]/items/  are the ids of the LearningResource for the children. Also, neither api call returns the  position or relationship type of the child items from LearningResourceRelationship

**Comment by mbertrand** [comment]
I think the `api/v1/learning_resources/[parent_id]/items/` endpoint is still needed for showing the episodes in a podcast.   It can be used to show courses in a program too, though that is currently displayed under the nested `{program: {courses:}}`  attribute anyway.

**Comment by mbertrand** [comment]
I think it might be good to use the same term (either /resources or /items), with the same output format (which would need to include position and ID to be compatible with CRUD where needed).
