### ISSUE TITLE
"author" field in LearningPath serializer: is it necessary?

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#328]
# Description/Context
The `LearningPath` serializer currently includes an `author` field whose value is equal to the id of the user who created it.  

Is this field going to be used for anything? If so, would `username` or `name` be better?  If not, it should be excluded from the serializer data output.

```
        "learning_path": {
            "id": 1,
            "item_count": 0,
            "author": 1
        },
```

**Comment by ChristopherChudzicki** [comment]
IMO, we should exclude it from the API response. Whenever we've discussed learning paths, they are communally owned by a group of users.
