### ISSUE TITLE
contentfiles/ endpoint is extraordinarily slow

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#386]
### Description/Context
1. Visit https://mitopen-rc.odl.mit.edu/api/v1/contentfiles/ or `curl https://mitopen-rc.odl.mit.edu/api/v1/contentfiles/` for better timing
2. The API takes about 20 seconds to send back 10kb data

### Plan/Design (RFC)

The initial PR for fixing this issue made the following changes:
- Delete contentfiles for unpublished courses/runs (lowering the total count)
- Add a database index on the `created_on` fields of models inheriting from `TimestampedModel`, and order the contentfiles by `-created_on`

These changes helped a bit, but not enough (from ~20 seconds to ~10 seconds with default limit/offset values on RC with ~700K contentfiles).  Also, when the offset value is increased significantly (like `offset=500000`), the response time gets far worse.

The following additional changes may improve things further:

### Sort by `-id` instead of `-created_on`.    
In retrospect the indexing of the `created_on` field was probably redundant and could perhaps be removed.   Sorting by `id` instead of `created_on` should retrieve the results in the same order. In preliminary testing, queries that sorted by `-id` were much faster than queries sorted by `-created_on`, even though both are now indexed on RC.  

### Remove the `unpublished=True` filter.  

Since unpublished contentfiles are now being deleted, this is also redundant.  Only published contentfiles should be in the database.

### CursorPagination : The good the bad, and the ugly
We could switch to cursor pagination for the `/api/v1/contentfiles` endpoint, but continue using default limit/offset pagination for the nested `/api/v1/<resource_id>/contentfiles` endpoint.

Good: According to the documentation, cursor pagination is ideal for large querysets:  "With extremely large datasets pagination using offset-based pagination styles may become inefficient or unusable. Cursor based pagination schemes instead have fixed-time properties, and do not slow down as the dataset size increases."

Bad: Ordering should always be on an indexed field with unique (or almost unique), non-null, non-float values.  This should be okay because right now it is only ordered by `-created_on` and the proposed sorting by `-id` also meets this requirement.

Ugly:  It is not possible to have arbitrary offset values in urls to grab a certain range of results from anywhere within the total set of results, for instance `offset=1200&limit=10`.   There are only `next` and `previous` urls provided for any given cursor that the user/api-bot would need to use to navigate through the results.  Furthermore, the cursor-based url parameters are not nearly as user-friendly: `?cursor=cD0xMTExMjE%3D` vs `?offset=20&limit=10`.   

![Screenshot 2024-01-25 at 1 25 31 PM](https://github.com/mitodl/mit-open/assets/187676/1bc8640b-7017-4660-978f-ce182ff85d2d)

However, offset and limit parameters could still be used for the contentfiles nested under the learning_resouces API endpoint.

![Screenshot 2024-01-25 at 3 02 00 PM](https://github.com/mitodl/mit-open/assets/187676/92a1eb22-0c95-448d-809d-9d876fe00774)

### Option B: Remove the endpoint altogether
Contentfiles can already be accessed via the `/api/v1/learning_resources/<resource_id>/contentfiles/` endpoint, which does not have performance problems because a much smaller number of contentfiles is returned per resource - if that is good enough, then the `/api/v1/contentfiles/` endpoint could just be removed.

**Comment by mbertrand** [comment]
One culprit for the slow performance might be the sort on `-updated_on` in the `ContentFileViewSet`.  This is not an indexed field.  Removing it made the query signficantly faster in local testing.  So might be able to improve performance by indexing the `updated_on` field or removing that sort if it is not really needed.

**Comment by mbertrand** [comment]
Closing again, this doesn't seem to be a problem on production, and RC was much better once a full vacuum analyze was done on the table.
