### ISSUE TITLE
Search API: `resource_type: content_file` included in aggregations even though not a `resource_type`

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#389]
We have five resource types (`course`, `video`, `podcast`, `podcast_episode`, `learning_path`). The `aggregations` property on search API results includes a sixth type, `content_file`:
```json
{
  "aggregations": {
    "resource_type": [
      { "key": "content_file", "doc_count": 649194 },
      { "key": "course", "doc_count": 3199 },
      { "key": "podcast_episode", "doc_count": 2358 },
      { "key": "podcast", "doc_count": 42 },
      { "key": "program", "doc_count": 12 },
      { "key": "learning_path", "doc_count": 2 }
    ],
    "certification": [
      { "key": "false", "doc_count": 3036 },
      { "key": "true", "doc_count": 163 }
    ]
  },
  "suggest": []
}
```

### Expected Behavior
`key` values under `aggregations.resource_type` should be valid resource types.

### Current Behavior
All valid, except additional key `content_file`.

### Steps to Reproduce
Inspect API results from https://mitopen-rc.odl.mit.edu/api/v1/learning_resources_search/?resource_type=course&aggregations=resource_type,certification

### Possible Solution
The `content_file` count could be valuable information, but shouldn't be under `resource_type`, since it's not a valid `resource_type`. It could be under a separate key:
```jsonc
aggregations: {
    resource_type: [...],
    content_files: [ { key: "all", value: 642578 } ]  // array or object?
}
```

**Comment by abeglova** [comment]
Right now the resource_type field is used to filter for content files https://github.com/mitodl/mit-open/blob/main/learning_resources_search/serializers.py#L277. We should add a new is_content_file boolean field for both learning resources and content files in the open search index and use that to do that filtering instead. Then we can remove the resource_type field from content files altogather
