### ISSUE TITLE
When tika errors on parsing an ocw file, save it without the content instead of not saving it at all

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#392]
Currently when tika throws an error when parsing a file that file is skipped. Instead we should save it with a title and other fields but no content. 

In particular https://ocw.mit.edu/courses/18-706-noncommutative-algebra-spring-2023/resources/mit18_706_s23_full_lec_pdf/
is not saved as a content file in the database and not added to the search  because tika throws an error when trying to parse it. https://mit-office-of-digital-learning.sentry.io/issues/4552201429/?project=216201&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

The error link is to legacy discussions because mitopen-rc get ocw data from ocw-content-live-qa which does not have this course. The relevant code is the same in mit-open and legacy discussions though. 

There is a separate issue for changing the source for ocw on rc to live ocw : https://github.com/mitodl/mit-open/issues/391.

**Comment by mbertrand** [comment]
This seems like maybe an open-discussions issue?  `course_catalog.tasks.get_ocw_next_courses` from the sentry issue doesn't exist on mit-open anymore, and there is code in mit-open to just log this exception and continue:  https://github.com/mitodl/mit-open/blob/main/learning_resources/etl/ocw.py#L153-L163

**Comment by mbertrand** [comment]
The contentfile mentioned above is returned in search results on prod and RC:

https://mitopen.odl.mit.edu/api/v1/content_file_search/?q=%2218.706%20(S23),%20Full%20Lecture%20Notes%22
https://mit-open-rc.odl.mit.edu/api/v1/content_file_search/?q=%2218.706%20(S23),%20Full%20Lecture%20Notes%22
