### ISSUE TITLE
tika times out on large documents

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#393]
Tika times out when parsing large documents (see https://github.com/mitodl/mit-open/issues/392 for context) . Is this something that can be improved? The observed error is on legacy discussions because mitopen-rc gets ocw data from ocw-content-live-qa which does not have this course. The relevant code is the same in mit-open and legacy discussions though.

**Comment by mbertrand** [comment]
```
TIKA_TIMEOUT = get_int("TIKA_TIMEOUT", 60)
```

This could be increased, though 60 seconds is already pretty long.

**Comment by mbertrand** [comment]
PS the `TIKA_TIMEOUT` setting is only present in mit-open, not open-discussions, but 60 seconds is the default used by tika anyway.  Will experiment with large files to see what the setting should be raised to.
