### ISSUE TITLE
Learning Resource Search: filter `?level=high_school` does not work (nor other multiword level filters).

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#431]
This issue affects the following endpoint:
- https://mitopen.odl.mit.edu/api/v1/learning_resources_search
- with filter `?level=high_school` OR `?level=noncredit`; other filters (platform, offered_by, etc) are not affected.

This isn't really related to #427, as evidenced by the "High School" aspect. 

### Expected Behavior
It should be possible to filter only courses with level high school.

### Current Behavior
Not possible.

### Steps to Reproduce
1. View the docs https://mitopen.odl.mit.edu/api/v1/schema/redoc/#tag/learning_resources_search; `?level=high_school` is how you're supposed to filter for high school courses.
2. View https://mitopen.odl.mit.edu/api/v1/learning_resources_search?level=high_school **No results**

### Possible Solution
Our resources store `level` as human readable strings with value imported from ETL sources without modification. But our APIs expect `?level=` filter values to be slugified strings:
```
data value,          API filterable value
--------------------------------------
Non-Credit           noncredit              <--- search does not work
High School          high_school            <--- search does not work
Undergraduate        undergraduate
Graduate             graduate
Introductory         introductory
Intermediate         Intermediate
Advanced             Advanced
```

**Options:** We could either:
1. continue filtering on an id-like value and implement a code change to make search work
    - this is what we do for `department`, `offered_by`, and `platform`
    - unlike for department, offered_by, and platform, the id-like value for "level" is only exposed via the OpenAPI docs, **not** in the returned data
2. filter (case-insensitively) directly on the human-readable value
    - this is what we do for `topic`

**Comment by ChristopherChudzicki** [comment]
It seems like we should go with (1), so that if we change "Non Credit" to "Noncredit" next year, the same filter still works? But should we additionally include the id-like value in the response?

**Comment by rhysyngsun** [comment]
Generally option 1 but a few thoughts:

-  Let's implement some code to make an algorithmic mapping of values:
   - Lowercase it
   - Replace `"-"` with `""`
   - Replace `\s+` (regex) with `"_"`
- If the resultant value matches one in our list, use that, otherwise log an error so we know we're getting some weird value.

Later on if there ends up being a lot of weird values we can look into a static mapping in addition to that but I think if that happens it'll be a small number of them.

**Comment by ChristopherChudzicki** [comment]
In discussing this issue with @abeglova, we realized another issue is that currently the search filters use id-like values (`high_school`, `noncredit`) but the aggregations use the labels (`{ key: "High School", doc_count: 123 }`). See aggregations at https://mit-open-rc.odl.mit.edu/api/v1/learning_resources_search/?aggregations=level.

It seems like we want:
- listed values of `level` filter in OpenAPI docs
- filters and aggregations should **both** use the id-like versions

In order to facilitate this, I would like to suggest that we change how we serialize LearningResourceRuns.

- **Now:** level only includes label:
    ```jsonc
    {
        "level": "High School",
        "platform:" { "code": "ocw", "name": "OCW" },
        "offered_by:" { "code": "ocw", "name": "OCW" }
    }
    ```
- **Proposed:** level only includes label:
    ```jsonc
    {
        "level": { "code": "high_school", "name": "High School" },
        "platform:" { "code": "ocw", "name": "OCW" },
        "offered_by:" { "code": "ocw", "name": "OCW" }
    }
    ```

This would (1) bring level in-line with platform and offered_by. And since the id-like level values are included in serialized data, it will be easy for search to filter **and** aggregate using the id-like values. 

**Question:** If the above makes sense, should we additionally change the LearningResourceRun model to store the id-like values for `level` rather than the labels? IMO, yes.

**Comment by rhysyngsun** [comment]
This makes sense and makes for a better API, regarding the human readable label I think you can also get that with a sub-aggregation but for such a limited and known set of values it's probably not worth the performance overhead. Alternatively, it'd be fine to have an API that returns the static set of values so we don't have to worry about updating the client.

**Comment by abeglova** [comment]
For now just making sure that 1) the filter values are the same across the apis and 2) The aggregation key is the same as the filter is enough
