### ISSUE TITLE
OCW Courses with no year/semester fail to import

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#441]
### Expected Behavior
Published OCW courses import successfully.

### Current Behavior
Some fail. For example, https://ocw.mit.edu/courses/res-hs-002-chemistry-behind-the-magic-chemical-demonstrations-for-the-classroom/ fails to import.

### Steps to Reproduce
In docker, run `./manage.py backpopulate_ocw_data --course-name=res-hs-002-chemistry-behind-the-magic-chemical-demonstrations-for-the-classroom`. This results in an error:
```
ValueError: Field 'year' expected a number but got ''.
```

### Possible Solution
Either:
- **This:** make the import script tolerate missing years (and semesters)
- ~or make the model property required and ensure all OCW courses have years / semesters~
    - ~But it seems reasonable that https://ocw.mit.edu/courses/res-hs-002-chemistry-behind-the-magic-chemical-demonstrations-for-the-classroom/ does not have a year~.

Confirmed with @pdpinch: Some "evergreen" OCW courses are expected to have no year/semesger

**Comment by ChristopherChudzicki** [comment]
I believe there are actually only two courses that are (1) published and (2) do not have year or semester. They are
- https://ocw.mit.edu/courses/res-hs-003-chemlab-boot-camp/
- https://ocw.mit.edu/courses/res-hs-002-chemistry-behind-the-magic-chemical-demonstrations-for-the-classroom/

**Comment by mbertrand** [comment]
This will have an impact on https://github.com/mitodl/mit-open/issues/423
