### ISSUE TITLE
API Tests should use string urls instead of `reverse()`

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mit-open#448]
### Description/Context
Most of our API tests use django's `reverse()` function to generate the url for an API. This can be problematic because the tests won't pick up on regressions introduced to the APIs by a change in a urls.py file. Frontend testing _might_ pick up on this but our APIs are increasingly being used outside of this application so verifying that API urls don't change is becoming more critical.

An example of this that we had to fix was the OCW webhook url changing accidentally: https://github.com/mitodl/mit-open/pull/442

**Comment by shanbady** [comment]
A check for api changes has already been implemented. closing
