### ISSUE TITLE
Prevent duplicate courses from being created if readable_id changes 

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#473]
Apparently it's possible for users to change the primary_course_number of an ocw course which creates a duplicate record for that course
https://github.com/mitodl/hq/issues/3499

Look into the best way to fix this. I think one option is to use the url to match to existing courses instead of the readable id (what primary_course_number is saved as) for ocw. Another is to send the old primary_course_number in the webhook request when the primary_course_number changes in studio.

**Comment by abeglova** [comment]
Looks like there is likely related  issue for Sloan executive education courses. For example
https://mitopen.odl.mit.edu/api/v1/learning_resources_search/?id=2884
and
https://mitopen.odl.mit.edu/api/v1/learning_resources_search/?id=2663
are the same course with a run with "start_date": "2024-03-05T12:00:00Z"

I think most sloan executive education course have duplicates

**Comment by mbertrand** [comment]
Seems like prolearn returns multiple results for some courses, which is passed on to mitopen, for example if you go to https://prolearn.mit.edu/courses-programs and search for "Breakthrough Customer Experience", four results are returned including the 2 mentioned above plus 2 more.  But the `course_application_url` field returned by the API is the same for all four.
