### ISSUE TITLE
LearningPath items api endpoint is broken

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#489]
Affter adding an item to a learning path, an error occurs trying to retrieve that item via API

### Steps to Reproduce
- Create a learning path via API if you don't already have on at http://localhost:8063/api/v1/learningpaths/
- Add an item to that learning path at http://localhost:8063/api/v1/learningpaths/5556/items/:
```
{
    "child": <resource_id>
}
```
You will get an error posting or after reloading the above url, caused by the `level` field

### Additional Details

```
web-1                    |   File "/src/learning_resources/serializers.py", line 151, in to_representation
web-1                    |     return {"code": value, "name": LevelType[value].value}
web-1                    |                                    ~~~~~~~~~^^^^^^^
web-1                    |   File "/usr/local/lib/python3.11/enum.py", line 790, in __getitem__
web-1                    |     return cls._member_map_[name]
web-1                    |            ~~~~~~~~~~~~~~~~^^^^^^
web-1                    | KeyError: 'Undergraduate'
```

**Comment by shanbady** [comment]
@mbertrand i wasnt able to reproduce this locally. Wondering if its a data issue or something that happens with a particular configuration of a learning path

**Comment by mbertrand** [comment]
Talked about it with Chris last Friday, Anastasia had the same problem locally, somehow our local docker databases ended up with a mix of old/outdated and new label values after the latest migration was applied.  But then I cleaned out my database, reverted to a previous commit, reimported all the data, and then reapplied the migration, and everything was fine.  Going to check RC again to make sure all looks good there in terms of label values, and if so, will close this issue.

**Comment by mbertrand** [comment]
RC label values still look good, something must have been off in the local docker database.  Closing the issue.
