### ISSUE TITLE
start_date is missing from most (all?) ocw courses

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#512]
https://ocw.mit.edu/search/?s=-runs.best_start_date&type=course
and 
https://live-qa.ocw.mit.edu/new-search/search/?e=resource&s=-start_date

look different - look into why that is

**Comment by abeglova** [comment]
The first result in the new ocw search is a course from 2001 - so the date sort in the new search is definitely broken

**Comment by mbertrand** [comment]
I think this is likely the result of [removing](https://docs.google.com/document/d/1t4xn0SjehhA1C_W--oC3L7HHkrPLdGnlEZQ-_Vj4qwI/edit#bookmark=id.rgu4gjf90s42) `best_start_date` as a  LearningResourceRun field, which in open-discussions would be calculated from the OCW semester and year:

> best_start_date: datetime (note: removing this field will 
require front-end logic to determine the best start date to display, and perhaps equivalent backend logic to filter API/search results by start date).

```
            "best_start_date": data.get("enrollment_start")
            or data.get("start")
            or utils.semester_year_to_date(semester, year),
```

We could add back in the `semester_year_to_date` function and apply it to the `start_date` field instead for OCW courses.

**Comment by mbertrand** [comment]
This could also be a problem elsewhere, because depending on the source and even within the same source, some courses might have a populated `enrollment_start_date` but a null `start_date` or vice versa - which is why `best_start_date` was created in open-discussions, to store the most relevant value of whichever field wasn't null.

**Comment by abeglova** [comment]
For ocw, just populating a start date based on the semester would be enough. Something like 09-01-YEAR for fall classes and 01-01-YEAR for spring. It's ok that there are a couple of ocw courses that don't have a semester and will show up in the end of the sort.

But probably we do want a best start date for non-ocw courses. It seems useful to be able to show either the soonest upcoming run or the latest finished run for mitx courses
