### ISSUE TITLE
E2E test for login

### ISSUE THREAD

**Issue by jonkafton** [mitodl/mit-open#536]
### Description/Context

The E2E test suite allows for testing outside the app itself, so can bring the OpenID authentication flow into test.

The spec should only run when pointed at RC or Prod (local is not configured for SSO).

- Assert that the user is logged out.
- Assert that an authenticated route cannot be accessed.
- Log in.
- Assert that the user is logged in.
- Assert that an authenticated route can be accessed.

### Plan/Design

- Create test users on RC and Prod.
- Create a [test tag](https://playwright.dev/docs/test-annotations#tag-tests) for tests intended to be pointed at live environments that won't run against local, e.g. `@nolocal`.
- Filter from the NPM `test` script for running locally (e.g. `--grep-invert @nolocal`)
- Write a test including the above tag.
  - Assert that the user is logged out. Can check the header user badge and menu.
  - Assert that the authenticated `/dashboard` route redirects to the SSO login.
  - Log in with email and password.
  - Assert that the user is redirected back to the dashboard screen and that it loads.
  - Assert that the header user badge has updated and that the menu contains links for authenticated users.

**Comment by pdpinch** [comment]
I don't understand what this will be able to actually test? Can you give me an example of the type of failure that could be caught by this? To put it another way, is the local development environment for keycloak similar enough to the deployed production environment that this can be a meaningful test?

**Comment by jonkafton** [comment]
Closing this one, https://github.com/mitodl/mit-open/pull/538#issuecomment-2061984783.
