### ISSUE TITLE
Add editable program letter template fields to program object

### ISSUE THREAD

**Issue by shanbady** [mitodl/mit-open#554]
The program letters we will be rendering will have some program specific elements. We should make these fields on the program object that we can edit via django admin
<img width="604" alt="Screenshot 2024-02-27 at 12 00 53 PM" src="https://github.com/mitodl/mit-open/assets/196425/31926c2f-a1e2-439b-ba0e-4b525d5073fb">

**Comment by pdpinch** [comment]
Even if only portions of the letter may be variable, I think it is prudent to make all the text customizable per program.

**Comment by Ferdi** [comment]
One option here is to leave the program letter config in MM portal.  While  We inted to wind down the MM portal for logged in learners,   the marketing pages are going to stay there for a while. If course teams use MM portal to edit their marketing pages (in wagtail), they might configure program letters there as well.

**Comment by pdpinch** [comment]
> One option here is to leave the program letter config in MM portal.

That's appealing. Would we pull the configuration data into mitopen through the data platform?

**Comment by Ferdi** [comment]
Probably better for MM to expose those settings as rest api , or something like that.

**Comment by shanbady** [comment]
@Ferdi closing this out as wont fix in favor of https://github.com/mitodl/hq/issues/3711
