### ISSUE TITLE
Authentication: registration flow

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mit-open#57]
Registration by email/password works by navigating to `/realms/olapps/login-actions/authenticate?client_id=account-console` on the Keycloak instance (not linking it publicly here).

Some currently documented rough edges:

- I was prompted to change my password immediately after creating the account via email/password. I'm assuming this to have to do with not having confirmed my email yet, but it's not great to have the user prompted to do this.

**Comment by shaidar** [comment]
That should be fixed now.
