### ISSUE TITLE
Endpoint to retrieve session data

### ISSUE THREAD

**Issue by jonkafton** [mitodl/mit-open#614]
### Description/Context

Working towards [RFC: Decouple the Frontend from the Backend Web Service #3646](https://github.com/mitodl/hq/discussions/3646).

Currently the web service injects session data into the base HTML template at [`{{ js_settings|json_script:'js-settings' }}`](https://github.com/mitodl/mit-open/blob/51587f10c0f18d171f28f09b5e7af92cd2525bad/main/templates/index.html#L19C7-L19C48).

When the web service is no longer serving the base HTML, the client app will need to fetch the authenticated user's session as it loads.

### Plan/Design

We need an endpoint, `GET /api/v1/session`, for example that returns the `user` object currently in the bootstrap with these properties:
```
{
  id: number
  first_name: string
  last_name: string
  is_authenticated: boolean
  is_learning_path_editor: boolean
  is_article_editor: boolean
}
```

**Comment by ChristopherChudzicki** [comment]
We do currently have https://mitopen-rc.odl.mit.edu/api/v0/users/me/, to which this information could be added.

One wrinkle is that it's a v0 endpoint. 
- The generated client **within** this repo only has v1 endpoints
- The generated client in https://github.com/mitodl/open-api-clients has v0 and v1, but must be released manually.

**Comment by ChristopherChudzicki** [comment]
> ... one reasonable approach is to have the /api/v1/users/me endpoint point to the same django view as /api/v0/users/me/ and enrich that view with the new fields.

- Keep the v0 api to avoid breaking @gumaerc work on https://github.com/mitodl/mit-open-login-button
- Add v1, with an OpenAPI note about it being "experimental" or "beta". Ideally we'd just use the v0, but, as mentioned above, there's no in-repo client for v0 and https://github.com/mitodl/open-api-clients isn't set up yet for publishing.

**Comment by shanbady** [comment]
The current /users/me endpoint gives a 403's if not authenticated - would it make sense to remove the 'is_authenticated' and rely on a 403 or is there some other reason we would need it to return something for anonymous users?
