### ISSUE TITLE
Endpoint to retrieve environment config

### ISSUE THREAD

**Issue by jonkafton** [mitodl/mit-open#615]
### Description/Context

Working towards [RFC: Decouple the Frontend from the Backend Web Service #3646](https://github.com/mitodl/hq/discussions/3646).

Currently the web service injects environment config into the base HTML template at [`{{ js_settings|json_script:'js-settings' }}`](https://github.com/mitodl/mit-open/blob/51587f10c0f18d171f28f09b5e7af92cd2525bad/main/templates/index.html#L19C7-L19C48).

When the web service is no longer serving the base HTML, the client app will need to fetch the environment config as it loads.

### Plan/Design

We need an endpoint, `GET /api/v1/environment`, for example, that returns the bootstrap object with these properties:
```
{
  embedlyKey: string
  ocw_next_base_url: string
  search_page_size: number
  ckeditor_upload_url: string
  environment: string
  sentry_dsn: string
  release_version: string
}
```

The user session object is covered by https://github.com/mitodl/mit-open/issues/614.

It may be that these values must not change between release, in which case we have the alternative option of baking them to the front end HTML at build time. The base HTML will be served from CDN with a low TTL and will have the front end code version (or file hashes) included, so we can similarly include the environment values.

**Comment by ChristopherChudzicki** [comment]
Rather than an endpoint, would it make sense to embed this information in the frontend during webpack build?

**Comment by shanbady** [comment]
I agree with @ChristopherChudzicki on that. It might be better to embed this via webpack and eliminate the roundtrip to fetch this info

**Comment by jonkafton** [comment]
Yes agree - if they are known at build time and don't change between releases. I'd suggest adding `.env.rc.` and `.env.prod` files to supply the values with dotenv and Webpacks's [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/).
