### ISSUE TITLE
Load session from API and configure decoupled frontend for local development

### ISSUE THREAD

**Issue by jonkafton** [mitodl/mit-open#616]
### Description/Context

Working towards [RFC: Decouple the Frontend from the Backend Web Service #3646](https://github.com/mitodl/hq/discussions/3646).

Depends on:
- https://github.com/mitodl/mit-open/issues/614
- https://github.com/mitodl/mit-open/issues/615

This task covers building the base HTML template with Webpack and serving it for local development.

There is a reference branch here: https://github.com/mitodl/mit-open/compare/main...jk/frontend-dev-server that provides a base HTML template and adds the `html-webpack-plugin` to inject the front end assets.

The `watch` container currently watches for front end build changes and shares a root directory volume mount with the `web` service. This container can be repurposed to run Webpack Dev Server to serve the front end.

### Plan/Design

- Add the `html-webpack-plugin` and base HTML template.

- Add an NPM script to serve locally:
```
"start-dev:local": "ENVIRONMENT=local NODE_ENV=development webpack serve"
```

- We can also run the front end locally and point to hosted environments, so for RC can add:
```
"start-dev:rc": "API_BASE_URL=https://mit-open-rc.odl.mit.edu ENVIRONMENT=local NODE_ENV=development webpack serve"
```

- Fetch the user session from the new endpoint from https://github.com/mitodl/mit-open/issues/614 (remove the hardcoded `window.SETTINGS` if using the reference branch).

- Front end code to fetch the environment data from the new endpoint from https://github.com/mitodl/mit-open/issues/615 _or_ we may instead bootstrap that during build and can use the [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/).

- For the `watch` container:
  - Remove the `.:/src` volume mount.
  - Move the build context to `./frontends`.
  - I would suggest moving `Dockerfile-node` to `./frontends` and repurposing for Webpack Dev Server.
 
- Clean out the `collectstatic` task from the web service. This gathers static assets for serving in the `web` service, which will now be served by the `watch` service. It might be an idea to rename `web` and `watch` to `backend` and `frontend`. Note we'll want zero impact to Django development, so need to establish workflows (does everyone use `docker compose up`?).

- We should also be able to remove the wait on the `watch` service in the `./scripts/run-django-dev.sh` script for developers wanting to run in production mode locally.

- The `./scripts/run-watch-dev.sh` script can be removed.

- The `./scripts/http-ok.sh` script can be removed.

- Update the `./conf/nginx.conf` config to proxy the `watch` container at root and static assets paths (likely the default route) and the `web` container at the API paths, `/api/*`.

**Comment by gumaerc** [comment]
> It might be an idea to rename `web` and `watch` to `backend` and `frontend`

+1 on this from me. I've always found it weird for the Node container to be named `watch`. The `web` container also technically "watches" for changes, but to Python files instead of JS. I think it makes way more sense to call them what they are, and `backend` and `frontend` is a literal, straightforward description. I like it.

**Comment by jonkafton** [comment]
The related PR is approved and ready to merge (https://github.com/mitodl/mit-open/pull/678) and the changes are aimed at compatibility with the existing deployment on Heroku to minimize any impact until we do the devops work for https://github.com/mitodl/mit-open/issues/629.

To ensure it can be merged and not block release, we need to configure the Nginx config for Heroku so that it serves the static front end. These changes have been applied to the local Nginx config in this PR, so it's a case of getting the config for Heroku to match and ensuring that the front end is built during CI and available there.
