### ISSUE TITLE
Clean up the apis and documentation for fields 

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#643]
### User Story
As part of https://github.com/mitodl/mit-open/pull/633/ fields were added to the v1 api. However the documentation at [/api/v1/schema/redoc/#tag/fields](https://mitopen.odl.mit.edu/api/v0/schema/redoc/#tag/fields/operation/fields_partial_update) is not up to the standards of the rest of the apis. Many fields do not currently have documentations. 

Additionally we need to figure out the following:
1) Are lists/featured lists still needed? How should they work?
2) Currently uploading a file to update avatars/banners is broken, fix it
3) How is the about param supposed to work? Currently it expects a json. What is the format of that json supposed to be?

**Comment by Ferdi** [comment]
- Good idea to fix the documentation
- We should leave lists/featured as they are in the backend 
- Fix avatars/banner
- About --  it should be simple html/ckeditor , but depends how much effort it'd take
