### ISSUE TITLE
Generate axios apis for v0 apis

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#648]
### Description/Context
In https://github.com/mitodl/mit-open/pull/633 I wanted to move api/v0/fields and api/v0/widget_lists into the v1 api in order to automatically generate axios api code for those endpoints. However, we are not going to put in the work clean up those apis to the standard of other v1 apis yet, so I will update the code to make them v0 again.

That means that we need to update ./scripts/generate_openapi.sh to auto generate clients for v0 apis in addition to v1 apis. I'm going to make this change in a seperate pr since it's unrelated to fields

**Comment by ChristopherChudzicki** [comment]
More reasons to do this:

- Our v1 APIs are more final; things that are experimental or that we do not want to appear in the generated documentation can remain `v0`. But we want to be able to use `v0` APIs in our frontend, so we need to generate the client.
- Modifying `mit-open` to generate both the v0 and v1 APIs is a small lift, and seems significantly easier than automating the publishing of https://github.com/mitodl/open-api-clients
