### ISSUE TITLE
The /new and /upcoming views don't stack with filters 

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#652]
The /new and /upcoming views don't stack with filters. The api ui lets you select filters but they are ignored.

https://mit-open-rc.odl.mit.edu/api/v1/learning_resources/new/?offered_by=xpro should filter to new xpro resources. Instead the xpro filter is ignored and all new resources are shown.

**Comment by abeglova** [comment]
I will evaluate how hard this is to fix - if it seems hard we can add /new and /upcoming to the search api and remove them from the django api instead

**Comment by mbertrand** [comment]
This should fix it (do the same for upcoming action):

```python
    def new(self, request: Request) -> QuerySet:  # noqa: ARG002
        queryset = self.get_queryset()
        filtered_queryset = self.filter_queryset(queryset)
        page = self.paginate_queryset(filtered_queryset.order_by("-created_on"))
 ```

**Comment by abeglova** [comment]
Thanks @mbertrand  that works
