### ISSUE TITLE
Add bookmark button to LearningResource cards

### ISSUE THREAD

**Issue by gumaerc** [mitodl/mit-open#721]
### Description/Context
Currently, if you are logged in as an administrator, you will see a button in the bottom right of `LearningResource` cards to add that `LearningResource` to a Learning Path. Now that the rest of the UI is in place to manage `UserList`s, we need a way to add `LearningResource`s  to them. A bookmark icon should appear in the bottom right of `LearningResource` cards, in place of the add to Learning Path button if not an admin or next to it if you are. Clicking this button should bring up a modal to add the resource to any of your `UserList`s.

### Plan/Design
 - [x] Modify or duplicate the "Add to Learning List" modal to support `UserList`s instead
   - [x] Title should say "Add to User List"
   - [x] Checkbox options should be `UserList`s and not Learning Paths
   - [x] Privacy level display should be based on `PrivacyLevelEnum` and show Public or Unlisted instead of Public / Private like Learning Paths
   - [x] The "Create a new list" button should show the `UserList` creation modal instead of the Learning Path one
 - [x] A bookmark icon button should be added to the bottom right of `LearningResource` cards
   - [ ] ~~The bookmark icon should use the outline style (`bookmark_border`) if the `LearningResource` is not part of any `UserList`s~~
   - [ ] ~~The bookmark icon should use the filled style (`bookmark`) if the `LearningResource` is part of a `UserList`~~
   - [x] Clicking the bookmark icon should display the "Add to User List" modal

**Comment by ChristopherChudzicki** [comment]
These two items:
   - [ ] The bookmark icon should use the outline style (`bookmark_border`) if the `LearningResource` is not part of any `UserList`s
   - [ ] The bookmark icon should use the filled style (`bookmark`) if the `LearningResource` is part of a `UserList`

are currently not feasible for the search page, btw. Blocked by https://github.com/mitodl/mit-open/issues/606
