### ISSUE TITLE
The channel ui does not display channels if the name has capital letters

### ISSUE THREAD

**Issue by abeglova** [mitodl/mit-open#751]
Since urls are all lowercase the channel ui can't find channels if their name has capital letters. Add a constraint that channel names should be lowercase and update the serializer to automatically lowercase channels names that are created/updated from the api or admin

**Comment by sovsey** [comment]
@abeglova Can you confirm if this is still an issue?

**Comment by sovsey** [comment]
Discussed with @abeglova, and we can close this ticket. Channel names are now automatically generated for units, topics, etc.
