### ISSUE TITLE
Allow users to "favorite" learning resources - backend

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#80]
# User Story
As a user, I want to bookmark some learning resources as "favorites"

# Description/Context
This is a port of existing functionality in open-discussions, where any authenticated user can add/remove courses, programs, videos, podcasts, and public lists as favorites.

# Acceptance Criteria
- [ ] Via an API, each user can list/unlist any learning resource as a favorite, and view their list of favorites. 

# Plan/Design
There are several possible ways to implement this:
a) as a `FavoriteItem` model with foreign keys to `LearningResource` and `User` (basically identical to the previous open-discussions approach)
b) as a special type of `UserList` - a "Favorites" `UserList`, of which there can be only one per user and which cannot be deleted.

**Comment by ChristopherChudzicki** [comment]
Another option, which is a product question for @Ferdi is:

c) As a normal `UserList`: when users create an account, they get a single, empty UserList called "Favorites". They can delete if they want. They can rename it (maybe to "Favourites" if they're Brits). They can delete it, and they can re-create it if they have regret about deleting.

Sort of like the "Documents" directory on my mac. It came pre-created, but it is, as far as I know, a normal directory that I can delete, etc.

**Comment by Ferdi** [comment]
If we go with option c)  ,  we don't need to do much from the backend/ api perspective , right ?

**Comment by ChristopherChudzicki** [comment]
> If we go with option c) , we don't need to do much from the backend/ api perspective , right ?

Correct. I believe the only thing we would need to do is create a "Favorites" list for each account / upon account creation.

**Comment by mbertrand** [comment]
Going with option C
