### ISSUE TITLE
Add "subscribe" button to topic pages

### ISSUE THREAD

**Issue by shanbady** [mitodl/mit-open#847]
All channel pages ([topic pages](https://mitopen-rc.odl.mit.edu/c/topic/math), [department pages](https://mitopen-rc.odl.mit.edu/c/department/history) and [offerer pages](https://mitopen-rc.odl.mit.edu/c/offeror/xpro)) should have a "subscribe/unsubscribe" toggle button modeled after similar buttons on the[ channel pages in open](https://open.mit.edu/login/?next=%2Fc%2Fbravenewplanet)
![Screenshot 2024-05-01 at 10 38 33 AM](https://github.com/mitodl/mit-open/assets/196425/b8cf1a62-e23a-48ba-9c5b-14f448ed2e33)

this will be a simple react component that checks the api on initialization to see if user is already subscribed and then display the appropriate state and allow them to sub/unsub. Since topic pages in mit-open are viewable without login, we should either hide the subscribe button or display it and have it so that clicking it forces authentication

**Comment by ChristopherChudzicki** [comment]
I think the behavior for anonymous users could use input from @Ferdi / @pdpinch / @steven-hatch ...  but hiding the button for anonymous users would be a good first step.

As for "forcing" authentication, we we get to it, the behavior of https://www.classcentral.com/universities 's "Follow" button is nice. ("Follow" is only visible when you hover the university items).
