### ISSUE TITLE
Populate Keycloak account profile with Touchstone information

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mit-open#87]
# User Story
As a Touchstone user, I expect my first name, last name, and email address to be automatically populated in my Keycloak account when I authenticate via Touchstone.

# Description/Context
1. You can initiate the MIT Open login workflow by visiting: https://mit-open-rc.odl.mit.edu/login/ol-oidc/
2. Touchstone will currently perform authentication.
3. Users, authenticating via Touchstone, are prompted by Keycloak for additional profile information (first name, last name, email address) before they are redirected back to MIT Open.
4. It is not known what information is passed from Touchstone to Keycloak.  
5. At a minimum, the following Keycloak account information should be automatically populated using data from Touchstone: first name, last name, email address.

# Acceptance Criteria
- [ ] User's can authenticate via Touchstone and be redirected back to the MIT Open application, without being prompted for additional account information.
- [ ] Documentation [here](https://docs.google.com/document/d/17tJ-C2EwWoSpJWZKjuhMVgsqGtyPH0IN9KakXvSKU0M/edit#heading=h.swsow4xcvm6d) is updated to reflect the user attributes provided by Touchstone.

**Comment by collinpreston** [comment]
@shaidar reaching out to IS&T to request that the SAML assertion contains firstName and lastName.  Right now we only receive mail (email) and displayName.

**Comment by shaidar** [comment]
Had a chat with folks in IST and they can release the givenName and sn as additional attributes for our SP. Submitting a ticket so that they can make that change.

**Comment by shaidar** [comment]
Submitted ticket to IST to release attributes for QA and Prod instances.

**Comment by shaidar** [comment]
This should be all set now.
