### ISSUE TITLE
Determine appropriate values for platform and offered_by

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#9]
Possible values for `platform` and `offered_by` are incorrect (for example, Micromasters should not be included in one or both).  Determine what the appropriate possible values are for each.

Current values:

```
class OfferedBy(Enum):
    """
    Enum for our Offered By labels. They are our MIT "brands" for LearningResources
    (Courses, Bootcamps, Programs) and are independent of what platform.
    User generated lists UserLists (like a learning path) don't have offered by "brand".
    Values are user-facing.
    """

    mitx = "MITx"
    ocw = "OCW"
    micromasters = "MicroMasters"
    bootcamps = "Bootcamps"
    xpro = "xPRO"
    oll = "Open Learning Library"
    csail = "CSAIL"
    mitpe = "Professional Education"
    see = "Sloan Executive Education"
    scc = "Schwarzman College of Computing"
    ctl = "Center for Transportation & Logistics"


class PlatformType(Enum):
    """
    Enum for platforms
    """

    ocw = "ocw"
    mitx = "mitx"
    mitxonline = "mitxonline"
    micromasters = "micromasters"
    bootcamps = "bootcamps"
    xpro = "xpro"
    oll = "oll"
    youtube = "youtube"
    podcast = "podcast"
    csail = "csail"
    mitpe = "mitpe"
    see = "see"
    scc = "scc"
    ctl = "ctl"
```

Correct values: TBD    

#### Designs and Mockups
TBD

#### Acceptance Criteria:

- [ ] TBD

**Comment by Ferdi** [comment]
offered by
It's an organization at MIT that offer the learning resource

ID |  Name | url 

ocw | MIT OpenCourseWare| http://ocw.mit.edu
mitx | MITx |   ?
bootcamps |  MIT Bootcamps | http://bootcamps.mit.edu
xpro | MIT xPRO | xpro.mit.edu
mitpe | MIT Professional Education | https://professional.mit.edu/
see |  MIT Sloan Executive Education |  https://exec.mit.edu/s/
horizon | MIT Horizon | https://horizon.mit.edu/


platfrom
The platform where the learning resource is hosted / consumed by learners.    For example, MITx offers learning resources in 2 different *platforms*,  edx.org and mitxonline.mit.edu

id  |  name | url
edx | edx | edx.org
mitxonline | MITx Online |  mitxonlihe.mit.edu
xpro | MIT xPRO |  xpro.mit.edu
emeritus | Emeritus |  ...
etc.

**Comment by mbertrand** [comment]
@Ferdi Where does micromasters fit into this? We are importing program data from the micromasters api at https://micromasters.mit.edu//api/v0/catalog/.   What are the appropriate `platform` and `offered_by` values for these programs?

**Comment by Ferdi** [comment]
"MicroMasters" is a specific type of program.
All programs of type "MicroMasters" are offered_by=MITx
DEDP program has platform=MITx Online
The rest of the programs have platfrom=edx.org

mm.mit.edu is not really a platform.  *I think* the reason we are  importing programs from there is because edx.org does not offer that information in their api.

**Comment by mbertrand** [comment]
@Ferdi in open-discussions, there are a bunch of `OfferedBy` values that are imported via podcasts (and videos?) not on the list above.  For example:

```
Arts at MIT
Broad Institute
CBMM
Center for International Studies
Department of Biology
Department of Urban Studies and Planning
Energy Initiative
J-PAL North America
Lex Fridman
MIT Alumni
MIT BLOSSOMS
MIT Climate
MIT Club of Boston
MIT Club of Northern California
MIT Comparative Media Studies
MIT Department of Biology
MIT Energy Initiative
MIT LGO
MIT Medical
MIT News
MIT Press
MIT Technology Review
Physics Technical Services Group
Professional Education
School of Humanities, Arts, and Social Sciences
The Martin Trust Center for MIT Entrepreneurship
Video Productions
```

Do we want these or not?  Or should we stick to an official list of valid values and set offered_by to null if the podcast/video value for it isn't in that list?

**Comment by mbertrand** [comment]
@Ferdi @pdpinch can you let me know if the below is correct?

Courses and programs imported from the Micromasters catalog API:
`offered_by` = `mitx`
`platform` = `edx` (except DEDP program, which is `mitx`) - there is no indication of this difference in the [API response ](https://micromasters.mit.edu/api/v0/catalog/)btw.  Will have to conditionally set to "mitx" if `"programpage_url" == "http://micromasters.mit.edu/dedp/"`. Will there be others in the future?

Courses and programs imported from the mitxonline catalog API:
`offered_by`: `mitx`
`platform`: `mitxonline`

Courses and programs imported from the Open Learning Library catalog API:
`offered_by`: `oll`
`platform`: `edx`???

Courses and programs imported from the bootcamps catalog API:
`offered_by`: `bootcamps`
`platform`: `edx`????

Courses and programs imported from the xpro catalog API:
`offered_by` = `xpro`
`platform` = `xpro` 

Courses and programs imported from OCW:
`offered_by`: `ocw`
`platform`: `ocw`

Most other courses/programs, like those imported from prolearn, `offered_by` and `platform` will be the same? For example,
Sloan Executive Education will be `offered_by` : `see` and `platform`: `see`

Podcasts: `platform`: `podcast` and `offered_by` depending on values in [this repo](https://github.com/mitodl/open-podcast-data/blob/master/podcasts/), but only if they match existing offered_by values in the database.

Videos: `platform`: `youtube`, `offered_by`: depending on values in [this repo](https://github.com/mitodl/open-video-data/tree/master/youtube), but only if they match existing offered_by values in the database.
 
Will there ever be more than one `offered_by` value for a course/program anymore? If so, which ones?

**Comment by mbertrand** [comment]
>Courses and programs imported from the xpro catalog API:
offered_by = xpro
platform = should be in the xpro API response now, look for it there.

@pdpinch @ferdi Looking at the xpro API response for courses, the possible values include "xPRO", "Emeritus", "Global Alumni", and lots of `null`.  Should the null ones really be null?  Or default to xpro?

**Comment by Ferdi** [comment]
I guess, can you check where some of the "null" ones run on xpro?

**Comment by mbertrand** [comment]
It's all over the place.

Some examples:

http://xpro.mit.edu/courses/course-v1:xPRO+IOTx/: 
- external_marketing_url https://executive-ed.xpro.mit.edu/Internet-of-things-iot-design-and-applications/?utm_campaign=school&utm_medium=MITWebsite&utm_source=MIT-web
- run courseware_urls: null

http://xpro.mit.edu/courses/course-v1:xPRO+LASERxE3/
- external_marketing_url: null
- run coursware urls: https://courses.xpro.mit.edu/courses/course-v1:xPRO+LASERxE3+R10/course/

http://xpro.mit.edu/courses/course-v1:xPRO+NANO/
- external_marketing_url: https://executive-ed.xpro.mit.edu/nanotechnology/?utm_campaign=school&utm_medium=MITWebsite&utm_source=MIT-web
- courseware_url(s): null

http://xpro.mit.edu/courses/course-v1:xPRO+PDT/
- external_marketing_url: https://globalalumni.xpro.mit.edu/en/courses/planning-for-digital-transformation-becoming-digital-ready/
- courseware_url(s): null

http://xpro.mit.edu/courses/course-v1:xPRO+BioEngx/
- external_marketing_url: null
- courseware_url(s): https://courses.xpro.mit.edu/courses/course-v1:xPRO+BioEngx+R13/course/
