### ISSUE TITLE
non-MVP: Keycloak user interface and experience designs

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mit-open#92]
# User Story
As a developer, I would like to build Keycloak pages and email templates that are based on mock-ups and designs.

# Acceptance Criteria
- [ ] Page designs exist for the following pages: login, registration email, registration password, password reset, account update.
- [ ] Email template designs exist for the following emails: registration validation, password reset, email change confirmation.

**Comment by sovsey** [comment]
Closing as duplicate of https://github.com/mitodl/hq/issues/4557.
