### ISSUE TITLE
Enable Keycloak logging & metrics

### ISSUE THREAD

**Issue by collinpreston** [mitodl/mit-open#94]
# User Story
As a Keycloak administrator, I want to be aware of issues within Keycloak.

# Description/Context
Determine:
1. What should be logged in Keycloak and what each log means
2. How long logs should persist in Keycloak.

# Acceptance Criteria

- [ ] Logging is enabled in Keycloak.
- [ ] [Documentation](https://docs.google.com/document/d/17tJ-C2EwWoSpJWZKjuhMVgsqGtyPH0IN9KakXvSKU0M/edit#heading=h.fl9n52btrpg6) is updated to explain what is logged and what it means.

**Comment by shaidar** [comment]
I added the metrics SPI to CI and QA and enabled metrics on the olapps realm. Those appear to be working and keycloak is generating events, however it is unable to POST to the configured Prometheus PushGateway as it's throwing a 404 page not found error. Tried tweaking the endpoint with no luck. Also tried a basic test using the python library and got the same result. Opened a support ticket with grafana to see what could be the issue and waiting to hear back.

**Comment by shaidar** [comment]
Keycloak logging and metrics are in place on CI and they're being shipped to grafana using the vector logging agent. I tried using [this keycloak metrics dashboard](https://grafana.com/grafana/dashboards/10441-keycloak-metrics-dashboard/) however it's fully functional as some of the metrics fields appear to have been renamed. Will need to take a closer look on Monday to get all the visuals in place.

**Comment by shaidar** [comment]
Added links and a basis overview to the doc
