### ISSUE TITLE
Store certification info in the database instead of calculating on the fly via properties

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#96]
# User Story
As an API user, I should be able to query for resources with or without certifications (and perhaps filter further by other certification attributes).  

# Description/Context
Currently, `LearningResource.certification` is a property that returns only the string "Certificates"  or null and is not stored in the database.  To facilitate query filtering by this field, and to provide further details on different types of certificates that some sites offer, a new `LearningResourceCertificate` model should be created, with fields TBD.

# Acceptance Criteria

- [ ] API returns certification info as part of response and can filter by this field (include/exclude resources with certificates, filter by resources with certain types of certificates)

# Plan/Design
 - Create new LearningResourceCertification model
- Add a nullable relationship between LearningResource and LearningResourceCertification
- Update the serializers/views to include certification info and filters for certificates

@ferdi @pdpinch I do not see any certification info in the current production API responses for xpro and very little for mitxonline (only field is `certificate_available_date`).

**Comment by pdpinch** [comment]
@mbertrand is this replaced by https://github.com/mitodl/hq/issues/3970 ?

Do we still need to add certificate info to the MITx Online and xPRO APIs?

**Comment by mbertrand** [comment]
Dupe of https://github.com/mitodl/hq/issues/3970
