### ISSUE TITLE
Change type/location of field for `professional offerings` vs `open content`

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#97]
# User Story
Users should be able to filter API responses by whether or not a `LearningResource` is a "Professional Offering" or not.  Currently that is stored in `LearningResourcePlatform.audience` but that should be changed.

# Description/Context
- Remove the `LearningResourcePlatform.audience`  field
- Add a `LearningResource.is_professional` boolean field (`True` if a "Professional Offering", False otherwise)
- Update the serializers and views as necessary  (Q: what are the opensearch implications if this is a boolean? )
- Add an API filter for this field
- For now, don't worry about "Open Content", which may or may not be the opposite of `is_professional`

# Acceptance Criteria

- [ ] User can filter the API response by `is_professional` == True or False

**Comment by mbertrand** [comment]
`is_professional` should be `True` for any resources **_offered by_**:

Bootcamps
xPRO
CSAIL
Professional Education
Sloan Executive Education
Schwarzman College of Computing
Center for Transportation and Logistics

and `False` for any others.

@Ferdi @pdpinch does the above look correct?

**Comment by Ferdi** [comment]
Yes
